apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: terraform-state-store
  namespace: terraform-state-store-store
spec:
  requestAutoCert: true
  exposeServices:
    console: true
    minio: true
  users:
    - name: terraform-state-store-user-0
  credsSecret:
    name: terraform-state-store-secret
  configuration:
    name: terraform-state-store-env-configuration
  pools:
    - resources: {}
      volumesPerServer: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - terraform-state-store
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-0
              topologyKey: kubernetes.io/hostname
      name: pool-0
      runtimeClassName: ''
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '10737418240'
          storageClassName: ssd-csi
        status: {}
  image: 'minio/minio:RELEASE.2024-06-13T22-53-53Z'
  features: {}
  mountPath: /export