apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-secret-operator-scc
  namespace: cluster-secret-operator
rules:
  - apiGroups: [ "security.openshift.io" ]
    resources: [ "securitycontextconstraints" ]
    verbs: [ "use" ]
    resourceNames: [ "nonroot-v2" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-secret-operator-scc
  namespace: cluster-secret-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-secret-operator-scc
subjects:
  - kind: ServiceAccount
    name: cluster-secret-operator-account
    namespace: cluster-secret-operator
---