apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "tenant-manifests.fullname" . }}
  labels:
    {{- include "tenant-manifests.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: service
    weight: 100
  wildcardPolicy: None