apiVersion: v1
kind: ConfigMap
metadata:
  name: data
  namespace: cloud-service
data:
  tenants: |
    - id: t0001
    - id: t0002
    - id: t0003
      source:
        path: tenant-manifests-alt
        helm:
          values: |
            ingress:
              enabled: false
