apiVersion: v1
kind: ConfigMap
metadata:
  name: data
  namespace: cloud-service
data:
  tenants: |
    - id: tenant1
    - id: tenant2
    - id: tenant3
      source:
        repoURL: https://github.com/ludydoo/poc-cloud-service-manifests
        path: tenant-manifests-alt
        helm:
          values: |
            serviceAccount:
              create: false