apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/ludydoo/poc-cloud-service
  labels:
    app: poc-cloud-service
    app.kubernetes.io/component: poc-cloud-service
    app.kubernetes.io/instance: poc-cloud-service
    app.kubernetes.io/name: poc-cloud-service
    app.kubernetes.io/part-of: poc-cloud-service-app
  name: poc-cloud-service
  namespace: cloud-service
spec:
  lookupPolicy:
    local: false