apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/ludydoo/poc-cloud-service
  name: cloud-service
  namespace: cloud-service-ci
spec:
  lookupPolicy:
    local: false