apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/ludydoo/poc-cloud-service
  name: poc-cloud-service
  namespace: cloud-service-ci
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: poc-cloud-service:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      ref: main
      uri: https://github.com/ludydoo/poc-cloud-service
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - generic:
        secretReference:
          name: generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: github-webhook-secret
      type: GitHub
---