
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/ludydoo/poc-cloud-service'
  name: poc-cloud-service
  namespace: cloud-service
  labels:
    app: poc-cloud-service
    app.kubernetes.io/component: poc-cloud-service
    app.kubernetes.io/instance: poc-cloud-service
    app.kubernetes.io/name: poc-cloud-service
    app.kubernetes.io/part-of: poc-cloud-service-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'poc-cloud-service:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/ludydoo/poc-cloud-service'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: poc-cloud-service-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: poc-cloud-service-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
